# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1006301bf43e8b03ebcc026fb7a88775e398c748b94ff941ccd0d5d67dfa568b63bec61dc1400dfb715fa959c033b0dcf8ed4a6ad149d75409fa2747b7c6e35

test:
  secret_key_base: f1049e2f2209321a901f3def5742d103a91a0cfba800d54f59c45c80bad1c5ceed3459d3044690e4394087e543d3993e672e7078375d440f33e9eef3eb37bf2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
